config/routes.rb
Rails.application.routes.draw do
  resources :teachers do
    resources :teacher_subjects, shallow: true
  end
  resources :subjects
  root to: 'subjects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects
  accepts_nested_attributes_for :teacher_subjects, allow_destroy: true

  validates :name, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_subjects, dependent: :destroy
  has_many :subjects, through: :teacher_subjects
  accepts_nested_attributes_for :teacher_subjects, allow_destroy: true

  validates :first_name, :last_name, presence: true

  def first_and_last_name
    "#{first_name} #{last_name}"
  end
end

app/models/teacher_subject.rb
class TeacherSubject < ApplicationRecord
  DEFAULT_LEVEL = 5

  belongs_to :teacher
  belongs_to :subject

  validates :teacher, uniqueness: {scope: :subject}, if: :_not_marked_for_destruction?

  validates :level, presence: true
  before_validation :_default_values_on_create, on: :create

  def _default_values_on_create
    self.level ||= DEFAULT_LEVEL
    # return value should be true or nil
    true
  end

  def _not_marked_for_destruction?
    # Rails validation does not work well when we update subject with
    # teacher_subjects_attributes when we mark_for_destruction
    subject.teacher_subjects.none?(&:_destroy)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show; end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit; end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params.merge(teacher_subjects_params))

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Class was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params.merge(teacher_subjects_params))
        format.html { redirect_to @subject, notice: 'Class was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(:name, :description)
  end

  def teacher_subjects_params
    return {} if params[:subject][:teacher_ids].nil?

    @subject.teacher_subjects.each(&:mark_for_destruction) if @subject.present?
    {
      teacher_subjects_attributes: params[:subject][:teacher_ids].reject(&:empty?).map { |id| {teacher_id: id} }
    }
  end
end

app/controllers/teacher_subjects_controller.rb
class TeacherSubjectsController < ApplicationController
  before_action :_set_teacher_subject, only: %i[show edit update destroy]
  before_action :_set_teacher, only: %i[new create]

  def edit; end

  def show; end

  def update
    if @teacher_subject.update(_teacher_subject_params)
      render :show
    else
      render :edit
    end
  end

  def new
    @teacher_subject = TeacherSubject.new level: TeacherSubject::DEFAULT_LEVEL
  end

  def create
    @teacher_subject = TeacherSubject.new _teacher_subject_params
    @teacher_subject.teacher = @teacher
    if @teacher_subject.save
      flash[:notice] = 'Class was successfully added'
    else
      render :new
    end
  end

  def destroy
    @teacher_subject.destroy!
    flash[:notice] = 'Class was successfully removed'
  end

  private

  def _set_teacher_subject
    @teacher_subject = TeacherSubject.find params[:id]
  end

  def _set_teacher
    @teacher = Teacher.find params[:teacher_id]
  end

  def _teacher_subject_params
    params.require(:teacher_subject).permit(:level, :subject_id)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[show edit update destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show; end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit; end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Classes', subjects_path %>
    <%= link_to 'Teachers', teachers_path %>
    <br>
    <%= yield %>
  </body>
</html>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class='field'>
    <%= form.select :teacher_ids, options_from_collection_for_select(Teacher.all, :id, :first_and_last_name, -> (teacher) { @subject.teacher_subjects.map(&:teacher_id).include? teacher.id }), {}, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Class</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Class</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subject.description %>
</p>

<p>
  <strong>Teachers</strong>
  <ul>
    <% @subject.teacher_subjects.each do |teacher_subject| %>
      <li><%= link_to teacher_subject.teacher.first_and_last_name, teacher_path(teacher_subject.teacher) %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/teacher_subjects/_create_form.html.erb
<div id='new-teacher-subject'>
  <%= form_with model: @teacher_subject, url: teacher_teacher_subjects_path(@teacher), create_remote: true do |form| %>
    <% if @teacher_subject.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@teacher_subject.errors.count, "error") %> prohibited this teacher from being saved:</h2>

        <ul>
          <% @teacher_subject.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :subject %>
      <%= form.select :subject_id, options_from_collection_for_select(Subject.all.where.not(id: @teacher.subjects), :id, :name) %>
    </div>

    <div class="field">
      <%= form.label :level %>
      <%= form.number_field :level %>
    </div>

    <div class="actions">
      <%= form.submit 'Add' %>
    </div>
  <% end %>
</div>

app/views/teacher_subjects/_form.html.erb
<li id='teacher-subject-<%= @teacher_subject.id %>'>
  <%= form_with model: @teacher_subject, remote: true do |form| %>
    <% if @teacher_subject.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@teacher_subject.errors.count, "error") %> prohibited this teacher from being saved:</h2>

        <ul>
          <% @teacher_subject.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.number_field :level %>

      <%= form.submit 'Update' %>
      <%= link_to 'Remove', teacher_subject_path(@teacher_subject), remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Cancel', teacher_subject_path(@teacher_subject), remote: true %>
    </div>
  <% end %>
</li>

app/views/teacher_subjects/_new.html.erb
<div id='new-teacher-subject'>
  <% if @teacher.subjects.size < Subject.all.size %>
    <%= link_to 'Add new class', new_teacher_teacher_subject_path(@teacher), remote: true %>
  <% else %>
    Please <%= link_to 'create new classes', new_subject_path %> so you can add to Teacher
  <% end %>
</div>

app/views/teacher_subjects/_show.html.erb
<%#
    teacher_subject
%>
<li id='teacher-subject-<%= teacher_subject.id %>'>
  <%= link_to teacher_subject.subject.name, subject_path(teacher_subject.subject) %> (<%= teacher_subject.level %>)
  <%= link_to 'Edit', edit_teacher_subject_path(teacher_subject), remote: true %>
</li>

app/views/teacher_subjects/create.js.erb
window.location.reload()

app/views/teacher_subjects/destroy.js.erb
var el = document.getElementById('teacher-subject-<%= @teacher_subject.id %>')
el.classList.add('hide');
el.classList.remove('show');
setTimeout(function() {
  window.location.reload()
}, 400);

app/views/teacher_subjects/edit.js.erb
document.getElementById('teacher-subject-<%= @teacher_subject.id %>').outerHTML = '<%= j render 'form' %>'

app/views/teacher_subjects/new.js.erb
document.getElementById('new-teacher-subject').outerHTML = '<%= j render 'create_form' %>'

app/views/teacher_subjects/show.js.erb
document.getElementById('teacher-subject-<%= @teacher_subject.id %>').outerHTML = '<%= j render 'teacher_subjects/show', teacher_subject: @teacher_subject %>'

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher_subject_form.html.erb
<%#
    form - we need parent form
%>
<%= form.fields_for :teacher_subjects do |ff| %>
  <%= ff.select
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

<p>
  <strong>Classes</strong>
  <ul>
    <% @teacher.teacher_subjects.each do |teacher_subject| %>
      <%= render 'teacher_subjects/show', teacher_subject: teacher_subject %>
    <% end %>
  </ul>
  <%= render 'teacher_subjects/new' %>
</p>